from collections.abc import Callable
from typing import Literal, final

from .certificates import VerificationCertificate

@final
class PureFunction:
    @property
    def certificate(self) -> VerificationCertificate: ...
    @property
    def __name__(self) -> str: ...
    def __call__(self, *args: object, **kwargs: object) -> object: ...

@final
class EffectFunction:
    @property
    def certificate(self) -> VerificationCertificate: ...
    @property
    def __name__(self) -> str: ...
    def __call__(self, *args: object, **kwargs: object) -> object: ...

@final
class _PreparedModule: ...

@final
class _RunTarget: ...

def verify_pure(
    function: Callable[..., object],
    declared_partials: tuple[str, ...] | None,
) -> PureFunction: ...
def verify_effect(
    function: Callable[..., object],
    declared_effects: tuple[str, ...] | None,
) -> EffectFunction: ...
def verify_record(record: type[object]) -> type[object]: ...
def fingerprint_distribution(name: str) -> tuple[str, str]: ...
def prepare_run_target(target: str) -> _RunTarget: ...
def verify_run_target(target: _RunTarget) -> str: ...
def run_verified_target(target: _RunTarget, arguments: list[str]) -> None: ...

def check_ast(payload: bytes) -> str: ...
def check_source(source: str, filename: str, source_sha256: str) -> str: ...
def encode_source(source: str, filename: str, source_sha256: str) -> bytes: ...
def prepare_module(
    source: str,
    filename: str,
    source_sha256: str,
) -> _PreparedModule: ...
def prepared_module_imports(module: _PreparedModule) -> str: ...
def check_prepared_runtime(module: _PreparedModule) -> str: ...
def check_prepared_runtime_project(
    modules: dict[str, _PreparedModule],
    root: str,
    external_symbols: str,
) -> str: ...
def check_prepared_target(
    modules: dict[str, _PreparedModule],
    root: str,
    target: Literal["file", "project"],
    policy: Literal["default", "deny_unsafe", "verified_only"],
) -> str: ...
def parse_external_signature(signature: str) -> str: ...
def check_project(payload: bytes) -> str: ...
def runtime_versions() -> tuple[int, str, int]: ...
