from __future__ import annotations

from .message_catalog import MessageTemplate

# The error catalog only contains messages that may reach the public Python API
# or CLI.
ERROR_MESSAGES = (
    MessageTemplate("protocol.json", "AST 协议 JSON 无效：{error}", "Invalid AST protocol JSON: {error}"),
    MessageTemplate("protocol.version", "不支持 AST 协议版本 {actual}，当前版本为 {expected}", "Unsupported AST protocol version {actual}; the current version is {expected}"),
    MessageTemplate("protocol.sha", "源码 SHA-256 格式无效", "The source SHA-256 has an invalid format"),
    MessageTemplate("protocol.language", "项目中的语言身份不一致", "Language identities in the project do not match"),
    MessageTemplate("effect.name.unknown", "未知效果名称 {name}", "Unknown effect name {name}"),
    MessageTemplate("effect.exception.invalid", "异常效果名称无效 {name}", "Invalid exception effect name {name}"),
    MessageTemplate("frontend.null", "Python 源码不能包含空字节", "Python source cannot contain null bytes"),
    MessageTemplate("frontend.module", "CPython 解析结果不是模块 AST", "The CPython parse result is not a module AST"),
    MessageTemplate("extension.diagnostics", "诊断序列化失败：{error}", "Diagnostic serialization failed: {error}"),
    MessageTemplate("extension.envelope.convert", "AST 信封转换失败：{error}", "AST envelope conversion failed: {error}"),
    MessageTemplate("extension.envelope.serialize", "AST 信封序列化失败：{error}", "AST envelope serialization failed: {error}"),
    MessageTemplate("cli.path.missing", "路径不存在：{path}", "Path does not exist: {path}"),
    MessageTemplate("cli.path.extension", "只支持 .py 文件：{path}", "Only .py files are supported: {path}"),
    MessageTemplate("cli.directory.symlink", "目录目标不能是符号链接：{path}", "A directory target cannot be a symbolic link: {path}"),
    MessageTemplate("cli.project.empty", "项目根目录不能只包含 __init__.py", "A project root cannot contain only __init__.py"),
    MessageTemplate("cli.module.path", "模块路径不是有效 Python 限定名：{path}", "The module path is not a valid Python qualified name: {path}"),
    MessageTemplate("cli.module.duplicate", "模块名 {name} 由多个源文件定义", "Module name {name} is defined by multiple source files"),
    MessageTemplate("core.diagnostics.invalid", "Rust 核心返回了无效诊断结构", "The Rust core returned an invalid diagnostic structure"),
    MessageTemplate("diagnostic.line.invalid", "诊断行号超出源码范围", "The diagnostic line is outside the source range"),
    MessageTemplate("diagnostic.column.invalid", "诊断字节列超出源码范围", "The diagnostic byte column is outside the source range"),
    MessageTemplate("diagnostic.effect_trace.frame", "效果来源包含无效帧", "The effect source contains an invalid frame"),
    MessageTemplate("diagnostic.effect_trace.location", "效果来源缺少文件或位置", "The effect source is missing a file or location"),
    MessageTemplate("diagnostic.effect_trace.list", "效果来源不是列表", "The effect source is not a list"),
    MessageTemplate("diagnostic.effect_trace.fields", "效果来源帧缺少必要字段", "An effect source frame is missing required fields"),
    MessageTemplate("diagnostic.effect_trace.span", "效果来源位置无效", "The effect source location is invalid"),
    MessageTemplate("decorator.effects.bare", "裸 @efct.effects 不接受效果参数", "Bare @efct.effects does not accept effect arguments"),
    MessageTemplate("decorator.effect.argument", "效果参数必须是字符串、强类型效果或强类型部分行为", "Effect arguments must be strings, typed effects, or typed partials"),
    MessageTemplate("decorator.effect.mixed", "字符串效果声明和强类型效果声明不能混用", "String and typed effect declarations cannot be mixed"),
    MessageTemplate("effect.namespace.construct", "效果命名空间 {name} 不能实例化", "Effect namespace {name} cannot be instantiated"),
    MessageTemplate("effect.raise.class", "Raise 需要一个异常类", "Raise requires an exception class"),
    MessageTemplate("effect.raise_group.class", "RaiseGroup 需要一个 Exception 类", "RaiseGroup requires an Exception class"),
    MessageTemplate("partial.exception.invalid", "异常部分行为名称无效 {name}", "Invalid exception partial name {name}"),
    MessageTemplate("partial.exception_group.invalid", "异常组部分行为名称无效 {name}", "Invalid exception group partial name {name}"),
    MessageTemplate("decorator.pure.bare", "裸 @efct.pure 不接受部分行为参数", "Bare @efct.pure does not accept partial arguments"),
    MessageTemplate("decorator.partial.mixed", "字符串部分行为声明和强类型部分行为声明不能混用", "String and typed partial declarations cannot be mixed"),
    MessageTemplate("decorator.partial.string", "pure 字符串声明必须是受支持的部分行为", "Pure string declarations must be supported partials"),
    MessageTemplate("decorator.partial.argument", "pure 参数必须是字符串或强类型部分行为", "Pure arguments must be strings or typed partial declarations"),
    MessageTemplate("decorator.pure.target", "@efct.pure 只能装饰 Python 函数或普通 Python 类", "@efct.pure only accepts Python functions or regular Python classes"),
    MessageTemplate("callable.pure.annotation", "PureCallable 只能用于类型标注", "PureCallable may only be used in type annotations"),
    MessageTemplate("callable.effect.annotation", "EffectCallable 只能用于类型标注", "EffectCallable may only be used in type annotations"),
    MessageTemplate("callable.effect_set.constraint", "EffectSet 只能用于效果泛型参数约束", "EffectSet may only be used as an effect-generic parameter constraint"),
    MessageTemplate("result.construct", "Result 必须通过 Ok 或 Err 构造", "Result must be constructed with Ok or Err"),
    MessageTemplate("frozen_map.tuple", "FrozenMap 构造器只接受元组", "The FrozenMap constructor only accepts a tuple"),
    MessageTemplate("frozen_map.item", "FrozenMap 元素必须是长度为二的元组", "Each FrozenMap item must be a two-element tuple"),
    MessageTemplate("frozen_map.pure", "FrozenMap 的键和值必须是深度不可变纯值", "FrozenMap keys and values must be deeply immutable pure values"),
    MessageTemplate("frozen_map.duplicate", "FrozenMap 禁止重复键", "FrozenMap does not allow duplicate keys"),
    MessageTemplate("record.registered", "纯记录 {name} 已经注册", "Pure record {name} is already registered"),
    MessageTemplate("arguments.positional", "位置参数数量过多", "Too many positional arguments"),
    MessageTemplate("arguments.duplicate", "参数 {name} 被重复赋值", "Argument {name} was assigned more than once"),
    MessageTemplate("arguments.unknown", "未知参数 {name}", "Unknown argument {name}"),
    MessageTemplate("arguments.missing", "缺少参数 {name}", "Missing argument {name}"),
    MessageTemplate("runtime.type.unhandled", "未处理的运行时类型变体", "Unhandled runtime type variant"),
    MessageTemplate("runtime.certificate.revoked", "Efct 证书已撤销：{reason}", "The Efct certificate has been revoked: {reason}"),
    MessageTemplate("runtime.global.constant", "全局名称 {name} 不是类型匹配的已验证纯常量", "Global name {name} is not a type-compatible verified pure constant"),
    MessageTemplate("runtime.pure_constructor.replaced", "efct 纯值构造器已被替换", "An efct pure-value constructor has been replaced"),
    MessageTemplate("runtime.dependency.bind", "无法绑定运行时依赖 {name}", "Runtime dependency {name} cannot be bound"),
    MessageTemplate("runtime.dependency.rebound", "运行时依赖 {name} 已被重新绑定", "Runtime dependency {name} has been rebound"),
    MessageTemplate("runtime.function.identity", "依赖函数 {name} 身份不匹配", "Dependency function {name} has an identity mismatch"),
    MessageTemplate("runtime.function.import", "依赖函数 {name} 与静态导入绑定不一致", "Dependency function {name} does not match its static import binding"),
    MessageTemplate("runtime.function.certificate", "依赖函数 {name} 与当前模块证书不一致", "Dependency function {name} does not match the current module certificate"),
    MessageTemplate("runtime.function.cross_certificate", "依赖函数 {name} 的跨模块证书不匹配", "Dependency function {name} has a mismatched cross-module certificate"),
    MessageTemplate("runtime.module.identity", "依赖模块 {name} 与静态导入绑定不一致", "Dependency module {name} does not match its static import binding"),
    MessageTemplate("runtime.module.certificate", "依赖模块 {name} 未包含在项目证书中", "Dependency module {name} is not included in the project certificate"),
    MessageTemplate("runtime.module.rebound", "依赖模块 {name} 已被重新绑定", "Dependency module {name} has been rebound"),
    MessageTemplate("runtime.module.member_rebound", "依赖模块 {name} 已被重新绑定", "Dependency module {name} has been rebound"),
    MessageTemplate("runtime.symbol.verified", "依赖符号 {name} 不是已验证函数", "Dependency symbol {name} is not a verified function"),
    MessageTemplate("runtime.symbol.certificate", "依赖符号 {name} 证书不匹配", "Dependency symbol {name} has a certificate mismatch"),
    MessageTemplate("runtime.registered.identity", "已登记模块 {name} 身份不匹配", "Registered module {name} has an identity mismatch"),
    MessageTemplate("runtime.registered.rebound", "已登记模块 {name} 已被重新绑定", "Registered module {name} has been rebound"),
    MessageTemplate("runtime.registered.symbol", "已登记符号 {name} 已被替换", "Registered symbol {name} has been replaced"),
    MessageTemplate("runtime.external.identity", "外部模块 {name} 身份不匹配", "External module {name} has an identity mismatch"),
    MessageTemplate("runtime.external.rebound", "外部模块 {name} 已被重新绑定", "External module {name} has been rebound"),
    MessageTemplate("runtime.external_symbol.rebound", "外部符号 {name} 已被重新绑定", "External symbol {name} has been rebound"),
    MessageTemplate("runtime.external_symbol.replaced", "外部符号 {name} 已被替换", "External symbol {name} has been replaced"),
    MessageTemplate("runtime.external_symbol.callable", "外部符号 {name} 不可调用", "External symbol {name} is not callable"),
    MessageTemplate("runtime.external_symbol.revalidate", "无法重新校验外部符号 {name}：{error}", "External symbol {name} cannot be revalidated: {error}"),
    MessageTemplate("runtime.audited.binding", "审计符号 {name} 与静态导入绑定不一致", "Audited symbol {name} does not match its static import binding"),
    MessageTemplate("runtime.audited.public_binding", "审计符号 {name} 与公开模块绑定不一致", "Audited symbol {name} does not match its public module binding"),
    MessageTemplate("runtime.audited.python_function", "审计符号 {name} 不是 Python 函数", "Audited symbol {name} is not a Python function"),
    MessageTemplate("runtime.audited.native_function", "审计符号 {name} 不是原生函数", "Audited symbol {name} is not a native function"),
    MessageTemplate("runtime.audited.code_origin", "审计符号 {name} 的代码来源不匹配", "Audited symbol {name} has a code origin mismatch"),
    MessageTemplate("runtime.audited.source_read", "无法读取审计源码 {path}：{error}", "Cannot read audited source {path}: {error}"),
    MessageTemplate("runtime.audited.source_digest", "审计符号 {name} 的安装源码摘要不匹配", "Audited symbol {name} has an installation source digest mismatch"),
    MessageTemplate("runtime.audited.source_locate", "无法在安装源码中唯一定位审计符号 {name}", "Audited symbol {name} cannot be uniquely located in its installation source"),
    MessageTemplate("runtime.audited.source_code", "审计符号 {name} 的代码与安装源码不匹配", "Audited symbol {name} code does not match its installation source"),
    MessageTemplate("runtime.audited.module_missing", "审计模块 {name} 尚未加载", "Audited module {name} is not loaded"),
    MessageTemplate("runtime.audited.module_identity", "审计模块 {name} 身份不匹配", "Audited module {name} has an identity mismatch"),
    MessageTemplate("runtime.audited.specification", "审计符号 {name} 没有模块规范", "Audited symbol {name} has no module specification"),
    MessageTemplate("runtime.audited.origin_missing", "审计符号 {name} 没有模块来源", "Audited symbol {name} has no module origin"),
    MessageTemplate("runtime.audited.origin_mismatch", "审计符号 {name} 的模块来源不匹配", "Audited symbol {name} has a module origin mismatch"),
    MessageTemplate("runtime.audited.file_metadata", "审计符号 {name} 的模块文件元数据不一致", "Audited symbol {name} has inconsistent module file metadata"),
    MessageTemplate("runtime.audited.implementation_identity", "审计符号 {name} 的实现身份不匹配", "Audited symbol {name} has an implementation identity mismatch"),
    MessageTemplate("runtime.audited.implementation_binding", "审计符号 {name} 与实现绑定不一致", "Audited symbol {name} does not match its implementation binding"),
    MessageTemplate("runtime.audited.implementation_globals", "审计符号 {name} 的实现全局环境不匹配", "Audited symbol {name} has an implementation globals mismatch"),
    MessageTemplate("runtime.audited.artifact_resolve", "无法解析审计产物 {path}：{error}", "Cannot resolve audited artifact {path}: {error}"),
    MessageTemplate("runtime.audited.replaced", "审计外部符号 {name} 已被替换", "Audited external symbol {name} has been replaced"),
    MessageTemplate("runtime.audited.code_identity", "审计外部符号 {name} 的代码身份不匹配", "Audited external symbol {name} has a code identity mismatch"),
    MessageTemplate("runtime.parameter.type", "参数 {name} 不满足精确类型 {type}", "Argument {name} does not satisfy exact type {type}"),
    MessageTemplate("runtime.return.type", "返回值不满足精确类型 {type}", "The return value does not satisfy exact type {type}"),
    MessageTemplate("runtime.pure_function.construct", "PureFunction 只能由验证器构造", "PureFunction can only be constructed by the verifier"),
    MessageTemplate("runtime.effect_function.construct", "EffectFunction 只能由验证器构造", "EffectFunction can only be constructed by the verifier"),
    MessageTemplate("runtime.record.class", "纯记录验证只接受普通 Python 类", "Pure record verification only accepts regular Python classes"),
    MessageTemplate("runtime.record.module", "无法定位纯记录所属模块", "The module containing the pure record cannot be located"),
    MessageTemplate("runtime.record.dataclass", "纯记录要求 @dataclass(frozen=True, slots=True)", "A pure record requires @dataclass(frozen=True, slots=True)"),
    MessageTemplate("runtime.record.slots", "纯记录要求 slots=True", "A pure record requires slots=True"),
    MessageTemplate("runtime.record.empty", "纯记录至少需要一个字段", "A pure record requires at least one field"),
    MessageTemplate("runtime.record.default", "纯记录字段禁止默认值和默认工厂", "Pure record fields cannot have defaults or default factories"),
    MessageTemplate("runtime.record.source", "纯记录要求可读取的 .py 源文件", "A pure record requires a readable .py source file"),
    MessageTemplate("runtime.cpython.version", "当前版本只支持 CPython 3.13 和 3.14", "The current version only supports CPython 3.13 and 3.14"),
    MessageTemplate("runtime.decorator.function", "Efct 装饰器只接受 Python 函数", "Efct decorators only accept Python functions"),
    MessageTemplate("runtime.function.shape", "MVP 禁止闭包和默认参数", "Closures and default arguments are not supported in the MVP"),
    MessageTemplate("runtime.function.module", "无法定位函数所属模块", "The module containing the function cannot be located"),
    MessageTemplate("runtime.function.locate", "无法在源码中唯一定位函数 {name}", "Function {name} cannot be uniquely located in the source"),
    MessageTemplate("runtime.function.code", "函数 {name} 的现场代码与源码不一致", "The live code for function {name} does not match the source"),
    MessageTemplate("runtime.function.return", "函数 {name} 缺少返回类型", "Function {name} is missing a return type"),
    MessageTemplate("runtime.source.required", "库模式要求可读取的 .py 源文件", "Library mode requires a readable .py source file"),
    MessageTemplate("runtime.source.read", "无法读取源码 {path}：{error}", "Cannot read source {path}: {error}"),
    MessageTemplate("runtime.source.extension", "库模式只接受可读取的 .py 源文件", "Library mode only accepts readable .py source files"),
    MessageTemplate("runtime.module_source.read", "无法读取模块源码 {path}：{error}", "Cannot read module source {path}: {error}"),
    MessageTemplate("runtime.source.identity", "函数代码路径与模块源码路径不一致", "The function code path does not match the module source path"),
    MessageTemplate("runtime.validation.reentry", "模块 {path} 验证发生重入", "Validation of module {path} was re-entered"),
    MessageTemplate("runtime.validation.failed", "模块 {path} 验证失败：{error}", "Validation of module {path} failed: {error}"),
    MessageTemplate("runtime.module.not_imported", "已声明依赖模块 {name} 尚未被导入", "Declared dependency module {name} has not been imported"),
    MessageTemplate("runtime.module.no_source", "依赖模块 {name} 没有可验证源码", "Dependency module {name} has no verifiable source"),
    MessageTemplate("runtime.module.read", "无法读取依赖模块 {name}：{error}", "Cannot read dependency module {name}: {error}"),
    MessageTemplate("runtime.module.extension", "依赖模块 {name} 不是可验证的 .py 源文件", "Dependency module {name} is not a verifiable .py source file"),
    MessageTemplate("runtime.module.path", "依赖模块 {name} 的路径不唯一", "Dependency module {name} does not have a unique path"),
    MessageTemplate("runtime_plan.function.locate", "无法在模块源码中唯一定位函数 {name}", "Function {name} cannot be uniquely located in the module source"),
    MessageTemplate(
        "runtime_plan.marker",
        "函数 {name} 的现场 Efct 标记与源码不一致；源码种类为 {source_kind}、声明为 {source_declarations}，现场种类为 {live_kind}、声明为 {live_declarations}",
        "The live Efct marker for function {name} does not match the source; source kind {source_kind} with declarations {source_declarations}, live kind {live_kind} with declarations {live_declarations}",
    ),
    MessageTemplate("runtime_plan.record.locate", "无法在模块中定位纯记录 {name}", "Pure record {name} cannot be located in the module"),
    MessageTemplate("runtime_plan.record.unverified", "纯记录 {name} 尚未通过验证", "Pure record {name} has not been verified"),
    MessageTemplate("runtime_plan.record.mismatch", "纯记录 {name} 与 Rust 运行时计划不一致", "Pure record {name} does not match the Rust runtime plan"),
    MessageTemplate("runtime_plan.parameters", "Rust 运行时计划中的参数名称与类型数量不一致", "The Rust runtime plan has mismatched parameter names and types"),
    MessageTemplate("runtime_plan.imports", "Rust 模块导入计划无效", "The Rust module import plan is invalid"),
    MessageTemplate("runtime_plan.signature", "Rust 外部签名结果无效", "The Rust external signature result is invalid"),
    MessageTemplate("trust.manifest.missing", "信任清单不存在：{path}", "Trust manifest does not exist: {path}"),
    MessageTemplate("trust.manifest.file", "信任清单必须是普通文件：{path}", "The trust manifest must be a regular file: {path}"),
    MessageTemplate("trust.manifest.parse", "无法解析信任清单 {path}：{error}", "Cannot parse trust manifest {path}: {error}"),
    MessageTemplate("trust.manifest.changed", "运行目标准备后信任清单发生变化", "The trust manifest changed after run target preparation"),
    MessageTemplate("trust.manifest.structure", "信任清单结构无效：{error}", "Invalid trust manifest structure: {error}"),
    MessageTemplate("trust.manifest.schema", "不支持信任清单 schema {actual}，当前 schema 为 {expected}", "Unsupported trust manifest schema {actual}; the current schema is {expected}"),
    MessageTemplate("trust.manifest.empty", "信任清单必须至少包含一个符号", "A trust manifest must contain at least one symbol"),
    MessageTemplate("trust.manifest.python_required", "包含审计符号的信任清单必须包含 python 表", "A trust manifest containing audited symbols requires a python table"),
    MessageTemplate("trust.manifest.python_forbidden", "不含审计符号的信任清单不能包含 python 表", "A trust manifest without audited symbols cannot contain a python table"),
    MessageTemplate("trust.manifest.distributions_forbidden", "不含审计符号的信任清单不能包含 distribution", "A trust manifest without audited symbols cannot contain distributions"),
    MessageTemplate("trust.symbol.duplicate", "信任符号 {name} 重复", "Trust symbol {name} is duplicated"),
    MessageTemplate("trust.entry.path", "信任条目 {index} 的 path 必须是限定符号名", "The path in trust entry {index} must be a qualified symbol name"),
    MessageTemplate("trust.entry.implementation_path", "信任条目 {index} 的实现路径必须是限定名", "The implementation path in trust entry {index} must be qualified"),
    MessageTemplate("trust.entry.owner", "信任条目 {index} 的 owner 无效", "Trust entry {index} has an invalid owner"),
    MessageTemplate("trust.entry.effects", "信任条目 {index} 的 effects 字段只能包含外部效果", "Field effects in trust entry {index} may only contain external effects"),
    MessageTemplate("trust.entry.partials", "信任条目 {index} 的 partials 字段只能包含部分行为", "Field partials in trust entry {index} may only contain partial behavior"),
    MessageTemplate("trust.entry.contract_duplicate", "信任条目 {index} 包含重复的效果或部分行为", "Trust entry {index} contains a duplicated effect or partial behavior"),
    MessageTemplate("trust.field.string", "字段 {field} 必须是非空字符串", "Field {field} must be a non-empty string"),
    MessageTemplate("trust.field.sha", "字段 {field} 必须是小写 SHA-256 摘要", "Field {field} must be a lowercase SHA-256 digest"),
    MessageTemplate("trust.audited.owner_missing", "审计符号 {path} 引用了不存在的 owner {owner}", "Audited symbol {path} references missing owner {owner}"),
    MessageTemplate("trust.audited.python_kind", "审计实现 {path} 不是 Python 模块", "Audited implementation {path} is not a Python module"),
    MessageTemplate("trust.audited.native_kind", "审计实现 {path} 不是原生扩展", "Audited implementation {path} is not a native extension"),
    MessageTemplate("trust.audited.cpython", "审计边界要求使用 CPython", "Audited boundaries require CPython"),
    MessageTemplate("trust.audited.python_version", "审计边界绑定 Python {expected}，当前版本为 {actual}", "Audited boundaries are bound to Python {expected}; the current version is {actual}"),
    MessageTemplate("trust.audited.implementation", "审计边界要求 {expected}，当前实现为 {actual}", "Audited boundaries require {expected}; the current implementation is {actual}"),
    MessageTemplate("trust.audited.cache_tag", "审计边界绑定 Python cache tag {expected}，当前 tag 为 {actual}", "Audited boundaries are bound to Python cache tag {expected}; the current tag is {actual}"),
    MessageTemplate("trust.signature.return", "外部符号签名必须包含返回类型：{signature}", "An external symbol signature must include a return type: {signature}"),
    MessageTemplate("trust.signature.invalid", "外部符号签名无效：{signature}", "Invalid external symbol signature: {signature}"),
    MessageTemplate("trust.signature.parameters", "外部符号签名只允许无默认值的普通已标注参数", "External symbol signatures only allow regular annotated parameters without defaults"),
    MessageTemplate("trust.signature.brackets", "外部符号签名括号不平衡", "External symbol signature brackets are unbalanced"),
    MessageTemplate("trust.signature.empty", "外部符号签名包含空参数类型", "The external symbol signature contains an empty parameter type"),
    MessageTemplate("trust.distribution.unused", "distribution {name} 未被任何审计符号使用", "Distribution {name} is not used by an audited symbol"),
    MessageTemplate("trust.distribution.entry_name", "distribution 条目 {index} 的名称无效", "Distribution entry {index} has an invalid name"),
    MessageTemplate("trust.distribution.name", "distribution 名称无效", "The distribution name is invalid"),
    MessageTemplate("trust.distribution.duplicate", "distribution {name} 重复", "Distribution {name} is duplicated"),
    MessageTemplate("trust.distribution.dependency_name", "distribution {name} 的依赖名称无效", "Distribution {name} has an invalid dependency name"),
    MessageTemplate("trust.distribution.dependency_duplicate", "distribution {name} 重复声明依赖 {dependency}", "Distribution {name} contains dependency {dependency} more than once"),
    MessageTemplate("trust.distribution.dependency_missing", "distribution {name} 引用了不存在的依赖 {dependency}", "Distribution {name} references missing dependency {dependency}"),
    MessageTemplate("trust.distribution.missing", "distribution {name} 不存在", "Distribution {name} is missing"),
    MessageTemplate("trust.distribution.not_installed", "distribution {name} 未安装", "Distribution {name} is not installed"),
    MessageTemplate("trust.distribution.version", "distribution {name} 绑定版本 {expected}，当前版本为 {actual}", "Distribution {name} is bound to version {expected}; the current version is {actual}"),
    MessageTemplate("trust.distribution.digest", "distribution {name} 的安装摘要已失效", "The installation digest for distribution {name} is no longer valid"),
    MessageTemplate("trust.distribution.metadata", "distribution {name} 的已安装元数据不一致", "Distribution {name} has inconsistent installed metadata"),
    MessageTemplate("trust.distribution.record", "distribution {name} 没有已安装文件记录", "Distribution {name} has no installed file record"),
    MessageTemplate("trust.distribution.path_duplicate", "distribution {name} 包含重复的已安装路径 {path}", "Distribution {name} contains duplicate installed path {path}"),
    MessageTemplate("trust.distribution.file_inspect", "无法检查 distribution 文件 {path}：{error}", "Cannot inspect distribution file {path}: {error}"),
    MessageTemplate("trust.distribution.file_regular", "distribution 文件 {path} 必须是普通文件且不能是符号链接", "Distribution file {path} must be a regular file and cannot be a symbolic link"),
    MessageTemplate("trust.distribution.path_alias", "distribution {name} 将多个已安装路径映射到 {path}", "Distribution {name} maps multiple installed paths to {path}"),
    MessageTemplate("trust.distribution.file_read", "无法读取 distribution 文件 {path}：{error}", "Cannot read distribution file {path}: {error}"),
    MessageTemplate("trust.distribution.editable", "审计 distribution {name} 不能以 editable 模式安装", "Audited distribution {name} cannot be installed in editable mode"),
    MessageTemplate("trust.distribution.module_duplicate", "distribution {name} 多次定义模块 {module}", "Distribution {name} defines module {module} more than once"),
    MessageTemplate("trust.symbol.owner", "符号 {symbol} 无法解析到 distribution {distribution} 所拥有的模块", "Symbol {symbol} does not resolve to a module owned by distribution {distribution}"),
    MessageTemplate("trust.implementation.missing", "实现 {symbol} 不属于审计 distribution 闭包", "Implementation {symbol} is not owned by the audited distribution closure"),
    MessageTemplate("trust.implementation.ambiguous", "实现 {symbol} 同时属于多个审计 distribution", "Implementation {symbol} is owned by multiple audited distributions"),
)
