from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class MessageTemplate:
    identifier: str
    zh_cn: str
    en: str


# The diagnostic catalog is independent of analyzers. Every diagnostic must
# provide both English and Simplified Chinese templates.
DIAGNOSTIC_MESSAGES = (
    MessageTemplate("python.syntax", "Python 语法错误：{message}", "Python syntax error: {message}"),
    MessageTemplate("typescript.disabled", "当前构建未启用 TypeScript 语言分析器", "The current build does not include the TypeScript analyzer"),
    MessageTemplate("python.payload.invalid", "Python 分析器收到了非 Python 语言负载", "The Python analyzer received a non-Python payload"),
    MessageTemplate("function.duplicate", "函数 {name} 重复定义", "Function {name} is defined more than once"),
    MessageTemplate("parameter.annotation.missing", "参数 {name} 缺少类型标注", "Parameter {name} is missing a type annotation"),
    MessageTemplate("parameter.boundary.invalid", "参数 {name} 的类型不能用于函数边界", "The type of parameter {name} cannot be used at a function boundary"),
    MessageTemplate("return.annotation.missing", "函数缺少返回值类型标注", "The function is missing a return type annotation"),
    MessageTemplate("return.boundary.invalid", "返回值类型不能用于函数边界", "The return type cannot be used at a function boundary"),
    MessageTemplate("declaration.duplicate", "声明 {declaration} 重复", "Declaration {declaration} appears more than once"),
    MessageTemplate("effect.declaration.explicit", "效果声明必须是字符串字面量或受支持的 efct.effect 或 efct.partial 构造器", "An effect declaration must be a string literal or a supported efct.effect or efct.partial constructor"),
    MessageTemplate("effect.declaration.mixed", "字符串效果声明和强类型效果声明不能混用", "String and typed effect declarations cannot be mixed"),
    MessageTemplate("partial.declaration.explicit", "部分行为声明必须是受支持的字符串或 efct.partial 构造器", "A partial declaration must be a supported string or efct.partial constructor"),
    MessageTemplate("partial.declaration.external", "pure 契约只能声明部分行为", "A pure contract may only declare partial behavior"),
    MessageTemplate("partial.declaration.mixed", "字符串部分行为声明和强类型部分行为声明不能混用", "String and typed partial declarations cannot be mixed"),
    MessageTemplate("type.any.forbidden", "禁止 Any", "Any is not allowed"),
    MessageTemplate("type.typing_any.forbidden", "禁止 typing.Any", "typing.Any is not allowed"),
    MessageTemplate("type.mutable_or_imprecise", "禁止可变或不精确类型 {type}", "Mutable or imprecise type {type} is not allowed"),
    MessageTemplate("type.mutable", "禁止可变类型 {type}", "Mutable type {type} is not allowed"),
    MessageTemplate("type.arguments.two", "{type} 需要两个类型参数", "{type} requires two type arguments"),
    MessageTemplate("pure_callable.arguments", "efct.PureCallable 需要参数类型列表和返回类型", "efct.PureCallable requires a parameter type list and a return type"),
    MessageTemplate("pure_callable.arity", "efct.PureCallable 需要两个类型参数", "efct.PureCallable requires two type arguments"),
    MessageTemplate("pure_callable.parameters", "efct.PureCallable 的第一个参数必须是类型列表", "The first argument to efct.PureCallable must be a type list"),
    MessageTemplate("pure_callable.boundary", "PureCallable 的参数和返回类型必须可用于函数边界", "PureCallable parameter and return types must be valid at function boundaries"),
    MessageTemplate("effect_callable.arguments", "efct.EffectCallable 需要参数类型列表、返回类型和效果变量", "efct.EffectCallable requires a parameter type list, a return type, and an effect variable"),
    MessageTemplate("effect_callable.arity", "efct.EffectCallable 需要三个类型参数", "efct.EffectCallable requires three type arguments"),
    MessageTemplate("effect_callable.parameters", "efct.EffectCallable 的第一个参数必须是类型列表", "The first argument to efct.EffectCallable must be a type list"),
    MessageTemplate("effect_callable.variable", "EffectCallable 的效果参数必须是已声明效果变量", "The EffectCallable effect argument must be a declared effect variable"),
    MessageTemplate("effect_variable.undeclared", "效果变量 {variable} 未声明", "Effect variable {variable} is not declared"),
    MessageTemplate("effect_callable.boundary", "EffectCallable 的参数和返回类型必须可用于函数边界", "EffectCallable parameter and return types must be valid at function boundaries"),
    MessageTemplate("annotation.unresolved", "无法解析类型标注", "The type annotation cannot be resolved"),
    MessageTemplate("value.unresolved", "无法解析值名称 {name}", "Value name {name} cannot be resolved"),
    MessageTemplate("constant.runtime.invalid", "该常量不能用于运行时表达式", "This constant cannot be used in a runtime expression"),
    MessageTemplate("mutable.container.escape", "局部可变对象不能嵌入容器逃逸", "A local mutable value cannot escape inside a container"),
    MessageTemplate("list.literal.binding", "列表字面量必须直接绑定到局部名称", "A list literal must be bound directly to a local name"),
    MessageTemplate("operator.unary.unsupported", "类型 {type} 不支持该一元运算", "Type {type} does not support this unary operation"),
    MessageTemplate("operator.boolean.unknown", "未知布尔运算符", "Unknown boolean operator"),
    MessageTemplate("operator.boolean.type", "布尔运算只接受精确 bool", "Boolean operations require exact bool values"),
    MessageTemplate("comparison.protocol.invalid", "比较表达式协议无效", "The comparison expression protocol is invalid"),
    MessageTemplate("comparison.types", "比较操作数类型不兼容", "Comparison operand types are incompatible"),
    MessageTemplate("comparison.operator.unsupported", "不支持该比较运算符", "This comparison operator is not supported"),
    MessageTemplate("conditional.condition", "条件表达式条件必须是精确 bool", "A conditional expression requires an exact bool condition"),
    MessageTemplate("conditional.branches", "条件表达式两侧类型必须完全相同", "Both branches of a conditional expression must have exactly the same type"),
    MessageTemplate("attribute.target", "属性只能作为已登记方法的调用目标", "An attribute may only be used as the target of a registered method call"),
    MessageTemplate("subscript.unsupported", "MVP 禁止运行时下标表达式", "Runtime subscript expressions are not supported in the MVP"),
    MessageTemplate("operator.binary.unsupported", "类型 {left} 和 {right} 不支持该二元运算", "Types {left} and {right} do not support this binary operation"),
    MessageTemplate("callback.effect_generic.unsupported", "暂不支持把效果泛型函数 {name} 作为回调传递", "Passing effect-generic function {name} as a callback is not supported yet"),
    MessageTemplate("callback.inferred_effect", "推导效果函数 {name} 不能作为一阶回调传递", "Inferred-effect function {name} cannot be passed as a first-order callback"),
    MessageTemplate("callback.inferred_contract", "具有推导效果或部分行为的函数不能作为一阶回调传递：{name}", "A function with inferred effects or partial behavior cannot be passed as a first-order callback: {name}"),
    MessageTemplate("list.append.type", "局部列表 append 参数类型不匹配", "The local list append argument has the wrong type"),
    MessageTemplate("method.unregistered", "未登记方法 {target}", "Method {target} is not registered"),
    MessageTemplate("call.target.static", "调用目标必须是静态名称或已登记方法", "A call target must be a static name or a registered method"),
    MessageTemplate("mutable.argument.escape", "局部可变对象不能作为调用参数逃逸", "A local mutable value cannot escape as a call argument"),
    MessageTemplate("pure_callable.call.types", "PureCallable 参数 {name} 的调用参数类型不匹配", "Arguments passed to PureCallable parameter {name} have the wrong types"),
    MessageTemplate("effect_callable.call.types", "EffectCallable 参数 {name} 的调用参数类型不匹配", "Arguments passed to EffectCallable parameter {name} have the wrong types"),
    MessageTemplate("call.shadowed", "名称 {name} 被不可调用值遮蔽", "Name {name} is shadowed by a non-callable value"),
    MessageTemplate("range.zero", "range 步长不能为零", "The range step cannot be zero"),
    MessageTemplate("range.static", "MVP 要求 range 步长是静态非零整数", "The MVP requires the range step to be a static non-zero integer"),
    MessageTemplate("record.call.types", "纯记录 {name} 的构造参数不匹配", "Constructor arguments for pure record {name} have the wrong types"),
    MessageTemplate(
        "record.fields.only",
        "纯记录只允许带类型标注的字段",
        "Pure records only allow annotated fields",
    ),
    MessageTemplate("frozenset.arguments", "frozenset 参数必须是非空同类元组", "frozenset requires a non-empty homogeneous tuple"),
    MessageTemplate(
        "pure_callable.contract",
        "参数不满足 PureCallable 要求的显式空效果与空部分行为契约",
        "The argument does not satisfy the explicit empty effect and partial contract required by PureCallable",
    ),
    MessageTemplate("function.call.types", "函数 {name} 的调用参数类型不匹配", "Arguments passed to function {name} have the wrong types"),
    MessageTemplate("external.call.types", "外部符号 {name} 的调用参数类型不匹配", "Arguments passed to external symbol {name} have the wrong types"),
    MessageTemplate("policy.audited", "当前策略拒绝 Audited 符号 {name}，边界 ID：{evidence}", "The current policy rejects audited symbol {name}; boundary ID: {evidence}"),
    MessageTemplate("policy.unsafe", "当前策略拒绝 Unsafe 符号 {name}：{reason}", "The current policy rejects unsafe symbol {name}: {reason}"),
    MessageTemplate("len.type", "len 不接受类型 {type}", "len does not accept type {type}"),
    MessageTemplate("str.exception.type", "str 不接受类型 {type}", "str does not accept type {type}"),
    MessageTemplate(
        "open.arguments",
        "open 参数类型不匹配",
        "open arguments have the wrong types",
    ),
    MessageTemplate(
        "open.mode.static",
        "文件模式必须是静态字符串字面量",
        "The file mode must be a static string literal",
    ),
    MessageTemplate(
        "open.mode.unsupported",
        "Python API 模型不支持该文件模式",
        "The file mode is not supported by the Python API model",
    ),
    MessageTemplate("print.type", "print 参数必须是受支持的纯值", "print arguments must be supported pure values"),
    MessageTemplate(
        "exception.constructor.arguments",
        "异常构造器 {exception} 要求零个参数或一个 str 参数",
        "Exception constructor {exception} requires zero arguments or one str argument",
    ),
    MessageTemplate(
        "exception_group.constructor.arguments",
        "ExceptionGroup 需要一个 str 消息和一个由已登记异常组成的非空元组",
        "ExceptionGroup requires a str message and a non-empty tuple of registered exceptions",
    ),
    MessageTemplate(
        "exception_group.child.class",
        "ExceptionGroup 的子项必须是异常实例，不能是 ExceptionGroup 类",
        "ExceptionGroup children must be exception instances, not the ExceptionGroup class",
    ),
    MessageTemplate(
        "exception_group.child.type",
        "ExceptionGroup 的子项必须是已登记异常实例或 ExceptionGroup 值",
        "ExceptionGroup children must be registered exception instances or ExceptionGroup values",
    ),
    MessageTemplate(
        "exception_group.custom.inheritance",
        "自定义异常不能继承 ExceptionGroup",
        "Custom exceptions cannot inherit from ExceptionGroup",
    ),
    MessageTemplate(
        "exception_group.declaration.leaf",
        "ExceptionGroup 声明必须指定已登记的叶子异常类型",
        "ExceptionGroup declarations must name their registered leaf exception types",
    ),
    MessageTemplate(
        "exception.type.unregistered",
        "异常类型 {exception} 未登记",
        "Exception type {exception} is not registered",
    ),
    MessageTemplate(
        "exception.string.qualified",
        "字符串异常声明必须使用完整限定的已登记名称",
        "A string exception declaration must use a fully qualified registered name",
    ),
    MessageTemplate(
        "exception.class.shape",
        "异常类要求一个基类，且不能使用装饰器或元类参数",
        "An exception class requires one base class and no decorators or metaclass arguments",
    ),
    MessageTemplate(
        "exception.class.docstring",
        "异常类文档字符串必须是类体的第一项",
        "An exception class docstring must be its first body item",
    ),
    MessageTemplate(
        "exception.class.body",
        "异常类体只能包含文档字符串和 pass",
        "An exception class body may only contain a docstring and pass",
    ),
    MessageTemplate(
        "exception.base.name",
        "异常基类必须是已登记异常类型名称",
        "An exception base must be a registered exception type name",
    ),
    MessageTemplate(
        "exception.class.duplicate",
        "异常类 {exception} 重复定义",
        "Exception class {exception} is defined more than once",
    ),
    MessageTemplate(
        "exception.base.unregistered",
        "异常基类 {exception} 未登记",
        "Exception base {exception} is not registered",
    ),
    MessageTemplate(
        "exception.base.chain",
        "异常类 {exception} 必须具有无环且最终指向 builtins.Exception 的基类链",
        "Exception class {exception} must have an acyclic base chain ending at builtins.Exception",
    ),
    MessageTemplate(
        "exception.base.order",
        "异常基类 {base} 必须先于子类 {exception} 定义",
        "Exception base {base} must be defined before subclass {exception}",
    ),
    MessageTemplate(
        "exception.identifier.invalid",
        "异常标识符 {exception} 无效",
        "Invalid exception identifier {exception}",
    ),
    MessageTemplate(
        "exception.symbol.collision",
        "模块名称 {name} 同时被定义为异常类和另一种符号",
        "Module name {name} is defined as both an exception class and another symbol",
    ),
    MessageTemplate("frozen_map.arguments", "FrozenMap 参数必须是非空且键值类型一致的二元组元组", "FrozenMap requires a non-empty tuple of consistently typed key-value pairs"),
    MessageTemplate("call.unregistered", "未登记调用目标 {name}", "Call target {name} is not registered"),
    MessageTemplate("record.duplicate", "纯记录 {name} 重复定义", "Pure record {name} is defined more than once"),
    MessageTemplate("record.field.duplicate", "纯记录字段 {name} 重复", "Pure record field {name} is defined more than once"),
    MessageTemplate("record.field.mutable", "纯记录字段 {name} 不是深度不可变纯值", "Pure record field {name} is not a deeply immutable pure value"),
    MessageTemplate("module.binding.conflict", "模块名称 {name} 同时定义为常量和函数", "Module name {name} is defined as both a constant and a function"),
    MessageTemplate("import.module.uncertified", "MVP 未认证导入模块 {path}", "Imported module {path} is not certified by the MVP"),
    MessageTemplate("import.symbol.uncertified", "MVP 未认证导入符号 {path}", "Imported symbol {path} is not certified by the MVP"),
    MessageTemplate("import.efct.required", "受检模块必须使用 `import efct`", "A checked module must use `import efct`"),
    MessageTemplate("constant.name", "模块常量 {name} 必须使用全大写名称", "Module constant {name} must use an uppercase name"),
    MessageTemplate("constant.duplicate", "模块常量 {name} 重复定义", "Module constant {name} is defined more than once"),
    MessageTemplate("constant.static", "模块常量初始化值必须可静态求值", "A module constant initializer must be statically evaluable"),
    MessageTemplate("return.missing", "非 None 函数存在未返回值的路径", "A non-None function has a path that does not return a value"),
    MessageTemplate("mutable.return.escape", "局部可变对象不能通过返回值逃逸", "A local mutable value cannot escape through a return value"),
    MessageTemplate("local.external", "纯函数局部值不能使用外部对象类型", "A local value in a pure function cannot use an external object type"),
    MessageTemplate("augmented.target", "增量赋值目标必须是局部名称", "An augmented assignment target must be a local name"),
    MessageTemplate("local.undefined", "局部变量 {name} 尚未定义", "Local variable {name} is not defined yet"),
    MessageTemplate("handler.binding.scope", "异常绑定 {name} 只在对应处理器内可用", "Exception binding {name} is only available inside its handler"),
    MessageTemplate("augmented.type", "增量赋值不能改变局部变量类型", "Augmented assignment cannot change a local variable type"),
    MessageTemplate("external.construct", "纯函数不能构造外部对象类型", "A pure function cannot construct an external object type"),
    MessageTemplate("raise.bare.cause", "无参数 raise 不能声明 cause", "A bare raise cannot declare a cause"),
    MessageTemplate("raise.cause.type", "raise 的 cause 必须是已登记异常或 None", "The raise cause must be a registered exception or None"),
    MessageTemplate("raise.bare.outside_handler", "无参数 raise 只能出现在异常处理器中", "A bare raise may only appear inside an exception handler"),
    MessageTemplate("raise.type", "raise 操作数必须是已登记异常", "The raise operand must be a registered exception"),
    MessageTemplate("break.outside_loop", "break 只能出现在循环中", "break may only appear inside a loop"),
    MessageTemplate("continue.outside_loop", "continue 只能出现在循环中", "continue may only appear inside a loop"),
    MessageTemplate("assignment.target", "赋值目标必须是局部名称", "An assignment target must be a local name"),
    MessageTemplate("binding.shadow", "禁止遮蔽模块绑定 {name}", "Module binding {name} cannot be shadowed"),
    MessageTemplate("list.binding", "局部列表必须直接绑定到局部名称", "A local list must be bound directly to a local name"),
    MessageTemplate("list.empty", "空列表无法推断元素类型", "The element type of an empty list cannot be inferred"),
    MessageTemplate("list.element.pure", "局部列表元素必须是受支持的纯值", "Local list elements must be supported pure values"),
    MessageTemplate("list.element.type", "局部列表元素类型必须完全一致", "All local list elements must have exactly the same type"),
    MessageTemplate("if.condition", "if 条件必须是精确 bool", "An if condition must be an exact bool"),
    MessageTemplate("tuple.iteration.type", "固定元组的所有迭代元素类型必须相同", "All iterated elements of a fixed tuple must have the same type"),
    MessageTemplate("tuple.iteration.empty", "无法从空元组推导循环变量类型", "A loop variable type cannot be inferred from an empty tuple"),
    MessageTemplate("tuple.index.type", "元组下标必须是精确 int", "A tuple index must be an exact int"),
    MessageTemplate("tuple.index.dynamic", "动态下标要求固定元组的元素类型一致", "A dynamic index requires a homogeneous fixed tuple"),
    MessageTemplate("frozen_map.key.type", "FrozenMap 键类型不匹配：需要 {expected}，得到 {actual}", "FrozenMap key type mismatch: expected {expected}, got {actual}"),
    MessageTemplate("index.unsupported", "类型 {type} 不支持下标", "Type {type} does not support indexing"),
    MessageTemplate("iteration.unsupported", "类型 {type} 不可在 MVP 中迭代", "Type {type} cannot be iterated in the MVP"),
    MessageTemplate("while.condition", "while 条件必须是精确 bool", "A while condition must be an exact bool"),
    MessageTemplate("match.subject.result", "受支持的 match 主体必须是 Result，不能是 {type}", "A supported match subject must be Result, not {type}"),
    MessageTemplate("match.efct.shadow", "Result 匹配中禁止遮蔽 efct 模块绑定", "The efct module binding cannot be shadowed in a Result match"),
    MessageTemplate("match.variant.duplicate", "Result 的 {variant} 模式重复且不可达", "The {variant} Result pattern is duplicated and unreachable"),
    MessageTemplate("match.exhaustive", "Result 匹配不完整，缺少 {variant}", "Result match is not exhaustive; missing {variant}"),
    MessageTemplate("match.pattern.explicit", "Result 匹配必须显式使用 efct.Ok 和 efct.Err 类模式", "A Result match must use explicit efct.Ok and efct.Err class patterns"),
    MessageTemplate("match.pattern.static", "Result 模式类必须是静态限定名称", "A Result pattern class must be a static qualified name"),
    MessageTemplate("match.pattern.class", "Result 匹配不支持类模式 {name}", "Class pattern {name} is not supported in a Result match"),
    MessageTemplate("match.pattern.payload", "Result 载荷模式必须是名称或通配符", "A Result payload pattern must be a name or wildcard"),
    MessageTemplate("match.pattern.arity", "Result 变体模式最多接受一个位置载荷", "A Result variant pattern accepts at most one positional payload"),
    MessageTemplate("try.handler_or_finally.required", "try 必须包含异常处理器或 finally 块", "A try statement must contain an exception handler or finally block"),
    MessageTemplate(
        "try_star.handler.required",
        "带 except* 的 try 必须至少包含一个处理器",
        "A try statement with except* must contain at least one handler",
    ),
    MessageTemplate("with.manager.required", "with 必须包含至少一个上下文管理器", "A with statement must contain at least one context manager"),
    MessageTemplate("with.manager.unsupported", "当前只支持 contextlib.suppress 上下文管理器", "Only contextlib.suppress is supported as a context manager"),
    MessageTemplate("suppress.exception.required", "contextlib.suppress 至少需要一个已登记异常类型", "contextlib.suppress requires at least one registered exception type"),
    MessageTemplate("suppress.exception.type", "contextlib.suppress 的参数必须是已登记异常类型名称", "contextlib.suppress arguments must be registered exception type names"),
    MessageTemplate("suppress.exception.overlap", "contextlib.suppress 的异常类型不能重叠", "contextlib.suppress exception types must not overlap"),
    MessageTemplate("finally.effect_variable", "不会正常完成的 finally 无法覆盖尚未解析的效果变量", "A non-fallthrough finally cannot override an unresolved effect variable"),
    MessageTemplate("finally.local.unavailable", "局部变量 {name} 未在 try 前定义，因此不能在 finally 中使用", "Local variable {name} is not available in finally because it was not defined before try"),
    MessageTemplate("finally.local.type", "finally 为局部变量 {name} 赋予了与正常路径不兼容的类型", "Finally assigns local {name} with a type incompatible with the normal path"),
    MessageTemplate("assert.condition.type", "assert 条件必须是精确 bool", "An assert condition must be an exact bool"),
    MessageTemplate("assert.message.type", "assert 消息必须是受支持的不可变数据值", "An assert message must be a supported immutable data value"),
    MessageTemplate(
        "handler.covered",
        "异常处理器类型已被前面的处理器覆盖，因此不可达",
        "The exception handler type is covered by an earlier handler and is unreachable",
    ),
    MessageTemplate(
        "handler.tuple.empty",
        "异常处理器类型元组不能为空",
        "An exception handler type tuple must not be empty",
    ),
    MessageTemplate(
        "handler.tuple.duplicate",
        "异常处理器类型 {exception} 重复",
        "Exception handler type {exception} appears more than once",
    ),
    MessageTemplate(
        "handler.tuple.overlap",
        "异常处理器类型 {first} 和 {second} 存在继承重叠",
        "Exception handler types {first} and {second} overlap by inheritance",
    ),
    MessageTemplate("handler.name", "异常处理器必须使用已登记的异常类型名称", "An exception handler must use a registered exception type name"),
    MessageTemplate("handler.type", "异常处理器类型 {name} 未登记或已被遮蔽", "Exception handler type {name} is unregistered or shadowed"),
    MessageTemplate(
        "handler.star.wrapper",
        "except* 处理器不能直接匹配 ExceptionGroup；请匹配其叶子异常类型",
        "An except* handler cannot match ExceptionGroup directly; match its leaf exception types",
    ),
    MessageTemplate(
        "handler.star.partial",
        "except* 处理器只能正常处理或重新抛出匹配子组；暂不支持抛出新的部分行为",
        "An except* handler may only handle normally or re-raise its matched subgroup; raising new partial behavior is not supported",
    ),
    MessageTemplate(
        "raise.operand.group",
        "raise 操作数必须是已登记异常或 ExceptionGroup",
        "The raise operand must be a registered exception or ExceptionGroup",
    ),
    MessageTemplate("type.mismatch", "类型不匹配：需要 {expected}，得到 {actual}", "Type mismatch: expected {expected}, got {actual}"),
    MessageTemplate("callee.invalid", "调用目标 {name} 未通过验证", "Call target {name} did not pass validation"),
    MessageTemplate("effect.undeclared", "函数 {name} 包含未声明效果 {effect}", "Function {name} contains undeclared effect {effect}"),
    MessageTemplate("partial.undeclared", "函数 {name} 包含未声明部分行为 {partial}", "Function {name} contains undeclared partial behavior {partial}"),
    MessageTemplate("effect.variable.undeclared", "函数传播了未声明效果变量 {variable}", "The function propagates undeclared effect variable {variable}"),
    MessageTemplate("effect.unused", "声明的效果 {effect} 未被使用", "Declared effect {effect} is not used"),
    MessageTemplate("partial.unused", "声明的部分行为 {partial} 未被使用", "Declared partial behavior {partial} is not used"),
    MessageTemplate("module.effect.undeclared", "模块初始化包含未声明效果 {effect}", "Module initialization contains undeclared effect {effect}"),
    MessageTemplate("module.partial.undeclared", "模块初始化包含未声明部分行为 {partial}", "Module initialization contains undeclared partial behavior {partial}"),
    MessageTemplate("module.effect.unused", "声明的模块初始化效果 {effect} 未被使用", "Declared module initialization effect {effect} is not used"),
    MessageTemplate("project.module.duplicate", "项目模块名 {name} 重复", "Project module name {name} is duplicated"),
    MessageTemplate("project.module.unresolved", "无法在受检项目中解析模块 {path}", "Module {path} cannot be resolved in the checked project"),
    MessageTemplate("project.dependency.invalid", "禁止循环或缺失依赖，涉及模块 {name}", "Cyclic or missing dependencies are not allowed; module involved: {name}"),
    MessageTemplate("external.certification", "外部符号 {path} 的认证无效：{message}", "Certification for external symbol {path} is invalid: {message}"),
    MessageTemplate("external.effect.duplicate", "外部效果 {effect} 重复", "External effect {effect} is duplicated"),
    MessageTemplate("external.evidence.empty", "外部信任证据不能为空", "External trust evidence cannot be empty"),
    MessageTemplate("external.symbol.duplicate", "外部符号重复", "The external symbol is duplicated"),
    MessageTemplate("external.type.argument.one", "类型 {type} 需要一个参数", "Type {type} requires one argument"),
    MessageTemplate("external.type.argument.two", "类型 {type} 需要两个参数", "Type {type} requires two arguments"),
    MessageTemplate("external.type.unsupported", "外部签名包含未支持类型 {type}", "The external signature contains unsupported type {type}"),
    MessageTemplate("external.type.brackets", "类型括号不平衡", "Type brackets are unbalanced"),
    MessageTemplate("external.type.empty", "类型参数不能为空", "A type argument cannot be empty"),
    MessageTemplate("lowering.import.relative_without_module", "禁止无模块名的相对导入", "A relative import without a module name is not allowed"),
    MessageTemplate("lowering.import.relative", "当前版本禁止相对导入", "Relative imports are not supported in the current version"),
    MessageTemplate("lowering.import.star", "禁止星号导入", "Star imports are not allowed"),
    MessageTemplate("lowering.constant.assignment", "模块常量必须是简单名称赋值", "A module constant must be assigned to a simple name"),
    MessageTemplate("lowering.constant.initializer", "模块常量必须有初始化值", "A module constant must have an initializer"),
    MessageTemplate("lowering.constant.target", "模块常量目标必须是名称", "A module constant target must be a name"),
    MessageTemplate("lowering.type_comment.function", "禁止函数类型注释", "Function type comments are not allowed"),
    MessageTemplate("lowering.record.bases", "纯记录禁止基类和元类", "Pure records cannot have base classes or metaclasses"),
    MessageTemplate("lowering.record.decorators", "纯记录类只能使用 @efct.pure 和 @dataclass(frozen=True, slots=True)", "A pure record class may only use @efct.pure and @dataclass(frozen=True, slots=True)"),
    MessageTemplate("lowering.record.default", "纯记录字段禁止默认值", "Pure record fields cannot have default values"),
    MessageTemplate("lowering.record.item", "纯记录禁止类体节点 {node}", "Pure records do not allow class body node {node}"),
    MessageTemplate("lowering.record.empty", "纯记录至少需要一个字段", "A pure record requires at least one field"),
    MessageTemplate("lowering.type_ignore", "禁止 # type: ignore", "# type: ignore is not allowed"),
    MessageTemplate("lowering.syntax", "不支持 Python 语法节点 {node}", "Python syntax node {node} is not supported"),
    MessageTemplate("lowering.marker.count", "函数必须恰好具有一个 Efct 标记", "A function must have exactly one Efct marker"),
    MessageTemplate("lowering.marker.allowed", "只允许 @efct.pure(...)、@efct.effects 或 @efct.effects(...) 标记", "Only @efct.pure(...), @efct.effects, or @efct.effects(...) markers are allowed"),
    MessageTemplate("lowering.module.contract.once", "模块只能声明一次 `_efct`", "A module may declare `_efct` only once"),
    MessageTemplate("lowering.module.contract.allowed", "`_efct` 模块契约必须是 `efct.pure(...)` 或 `efct.effects(...)`", "The `_efct` module contract must be `efct.pure(...)` or `efct.effects(...)`"),
    MessageTemplate("lowering.module.contract.direct", "`_efct` 模块契约必须直接赋值", "The `_efct` module contract must be assigned directly"),
    MessageTemplate("lowering.module.contract.empty", "纯模块必须声明 `_efct = efct.pure`，不能使用空效果集合", "A pure module must declare `_efct = efct.pure` instead of an empty effect set"),
    MessageTemplate("lowering.module.effect.name", "模块效果名称必须是字符串常量", "A module effect name must be a string literal"),
    MessageTemplate("lowering.module.contract.comment", "`_efct` 模块契约不能使用类型注释", "The `_efct` module contract cannot use a type comment"),
    MessageTemplate("lowering.module.assignment", "模块赋值必须是带标注的不可变常量", "A module assignment must be an annotated immutable constant"),
    MessageTemplate("lowering.module.statement.expression", "当前版本只支持模块初始化中的表达式语句", "The current version only supports expression statements in module initialization"),
    MessageTemplate("lowering.effect.name", "效果名称必须是字符串常量", "An effect name must be a string literal"),
    MessageTemplate("lowering.parameter.kind", "MVP 只允许没有默认值的普通参数", "The MVP only allows regular parameters without defaults"),
    MessageTemplate("lowering.effect_parameter.default", "效果泛型参数禁止默认值", "An effect-generic parameter cannot have a default value"),
    MessageTemplate("lowering.effect_parameter.constraint", "效果泛型参数必须显式约束为 efct.EffectSet", "An effect-generic parameter must be explicitly constrained to efct.EffectSet"),
    MessageTemplate("lowering.effect_parameter.only", "当前只支持 efct.EffectSet 泛型参数", "Only efct.EffectSet generic parameters are currently supported"),
    MessageTemplate("lowering.effect_parameter.kind", "只支持 efct.EffectSet 效果泛型参数", "Only efct.EffectSet effect-generic parameters are supported"),
    MessageTemplate("lowering.effect_parameter.duplicate", "效果泛型参数 {name} 重复声明", "Effect-generic parameter {name} is declared more than once"),
    MessageTemplate("lowering.type_comment.parameter", "禁止参数类型注释", "Parameter type comments are not allowed"),
    MessageTemplate("lowering.type_comment.assignment", "禁止赋值类型注释", "Assignment type comments are not allowed"),
    MessageTemplate("lowering.assignment.chain", "MVP 禁止链式赋值", "Chained assignment is not supported in the MVP"),
    MessageTemplate("lowering.type_assignment.target", "局部类型赋值目标必须是简单名称", "A local typed-assignment target must be a simple name"),
    MessageTemplate("lowering.type_comment.loop", "禁止循环类型注释", "Loop type comments are not allowed"),
    MessageTemplate("lowering.match.case", "match 必须至少包含一个 case", "A match statement must contain at least one case"),
    MessageTemplate("lowering.match.guard", "当前不支持 match guard", "Match guards are not currently supported"),
    MessageTemplate("lowering.match.keyword", "当前不支持关键字类模式", "Keyword class patterns are not currently supported"),
    MessageTemplate("lowering.match.as", "当前不支持 as 模式", "An as-pattern is not currently supported"),
    MessageTemplate("lowering.pattern", "不支持 Python 模式节点 {node}", "Python pattern node {node} is not supported"),
    MessageTemplate("lowering.handler.bare", "禁止使用裸 except，必须显式声明异常类型", "A bare except is not allowed; declare an exception type explicitly"),
    MessageTemplate("lowering.name.context", "未知名称上下文", "Unknown name context"),
    MessageTemplate("lowering.call.arguments", "MVP 调用只允许位置参数", "Calls in the MVP only allow positional arguments"),
    MessageTemplate("lowering.expression", "不支持 Python 表达式 {node}", "Python expression {node} is not supported"),
    MessageTemplate("lowering.constant", "不支持常量类型 {kind}", "Constant type {kind} is not supported"),
)


SUGGESTION_MESSAGES = (
    MessageTemplate("suggestion.effect.declare", "声明 @efct.effects(\"{effect}\") 或移除产生效果的操作", "Declare @efct.effects(\"{effect}\") or remove the effectful operation"),
    MessageTemplate("suggestion.partial.pure", "声明 @efct.pure(efct.partial.Raise(...)) 或移除部分操作 {partial}", "Declare @efct.pure(efct.partial.Raise(...)) or remove the partial operation {partial}"),
    MessageTemplate("suggestion.partial.effects", "声明 @efct.effects(efct.partial.Raise(...)) 或移除部分操作 {partial}", "Declare @efct.effects(efct.partial.Raise(...)) or remove the partial operation {partial}"),
    MessageTemplate("suggestion.module.partial.pure", "声明 `_efct = efct.pure(efct.partial.Raise(...))` 或移除部分操作 {partial}", "Declare `_efct = efct.pure(efct.partial.Raise(...))` or remove the partial operation {partial}"),
    MessageTemplate("suggestion.module.partial.effects", "声明 `_efct = efct.effects(efct.partial.Raise(...))` 或移除部分操作 {partial}", "Declare `_efct = efct.effects(efct.partial.Raise(...))` or remove the partial operation {partial}"),
    MessageTemplate("suggestion.partial.group.pure", "声明 @efct.pure(efct.partial.RaiseGroup(...)) 或移除部分操作 {partial}", "Declare @efct.pure(efct.partial.RaiseGroup(...)) or remove the partial operation {partial}"),
    MessageTemplate("suggestion.partial.group.effects", "声明 @efct.effects(efct.partial.RaiseGroup(...)) 或移除部分操作 {partial}", "Declare @efct.effects(efct.partial.RaiseGroup(...)) or remove the partial operation {partial}"),
    MessageTemplate("suggestion.module.partial.group.pure", "声明 `_efct = efct.pure(efct.partial.RaiseGroup(...))` 或移除部分操作 {partial}", "Declare `_efct = efct.pure(efct.partial.RaiseGroup(...))` or remove the partial operation {partial}"),
    MessageTemplate("suggestion.module.partial.group.effects", "声明 `_efct = efct.effects(efct.partial.RaiseGroup(...))` 或移除部分操作 {partial}", "Declare `_efct = efct.effects(efct.partial.RaiseGroup(...))` or remove the partial operation {partial}"),
    MessageTemplate("suggestion.partial.diverge.pure", "声明 @efct.pure(efct.partial.Diverge()) 或证明操作会终止", "Declare @efct.pure(efct.partial.Diverge()) or prove that the operation terminates"),
    MessageTemplate("suggestion.partial.diverge.effects", "声明 @efct.effects(efct.partial.Diverge()) 或证明操作会终止", "Declare @efct.effects(efct.partial.Diverge()) or prove that the operation terminates"),
    MessageTemplate("suggestion.module.partial.diverge.pure", "声明 `_efct = efct.pure(efct.partial.Diverge())` 或证明操作会终止", "Declare `_efct = efct.pure(efct.partial.Diverge())` or prove that the operation terminates"),
    MessageTemplate("suggestion.module.partial.diverge.effects", "声明 `_efct = efct.effects(efct.partial.Diverge())` 或证明操作会终止", "Declare `_efct = efct.effects(efct.partial.Diverge())` or prove that the operation terminates"),
    MessageTemplate("suggestion.module.effect.declare", "声明 `_efct = efct.effects(\"{effect}\")` 或移除产生效果的操作", "Declare `_efct = efct.effects(\"{effect}\")` or remove the effectful operation"),
    MessageTemplate("suggestion.effect_generic", "使用 @efct.effects 标记效果泛型函数，或移除回调调用", "Mark the effect-generic function with @efct.effects, or remove the callback invocation"),
    MessageTemplate("suggestion.effect.unused", "删除未使用的效果声明", "Remove the unused effect declaration"),
    MessageTemplate("suggestion.partial.unused", "删除未使用的部分行为声明", "Remove the unused partial declaration"),
    MessageTemplate("suggestion.module.effect.unused", "删除未使用的模块初始化效果声明", "Remove the unused module initialization effect declaration"),
    MessageTemplate("suggestion.syntax", "先修复 Python 语法错误", "Fix the Python syntax error first"),
)


OPERATION_MESSAGES = (
    MessageTemplate("operation.call.unsafe_external", "调用不安全外部符号 {name}", "Call unsafe external symbol {name}"),
    MessageTemplate("operation.call.external", "调用外部符号 {name}", "Call external symbol {name}"),
    MessageTemplate("operation.call.callback", "调用回调 {name}", "Invoke callback {name}"),
    MessageTemplate("operation.call", "调用 {name}", "Call {name}"),
    MessageTemplate("operation.raise.no_active_exception", "因为没有当前异常而抛出 {name}", "Raise {name} because no exception is active"),
    MessageTemplate("operation.raise", "抛出 {name}", "Raise {name}"),
    MessageTemplate("operation.reraise", "重新抛出 {name}", "Re-raise {name}"),
    MessageTemplate("operation.assert", "断言条件", "Assert condition"),
    MessageTemplate("operation.integer.floor_division", "整数整除", "Integer floor division"),
    MessageTemplate("operation.integer.modulo", "整数取模", "Integer modulo"),
    MessageTemplate("operation.tuple.index", "元组下标", "Index tuple"),
    MessageTemplate("operation.frozen_map.index", "FrozenMap 下标", "Index FrozenMap"),
    MessageTemplate("operation.frozen_map.construct", "构造 FrozenMap", "Construct FrozenMap"),
    MessageTemplate("operation.loop.repeat", "重复执行 while 循环", "Repeat while loop"),
    MessageTemplate("operation.call.recursive", "递归调用 {name}", "Recursive call to {name}"),
)
